package handlers

var MockListings = []Listing{
	{
		ID:            1,
		Title:         "Modern Loft in San Francisco",
		City:          "San Francisco",
		State:         "CA",
		ImageURL:      "https://picsum.photos/800/600?random=1",
		PricePerNight: 210.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.7, TotalReviews: 128},
	},
	{
		ID:            2,
		Title:         "Cozy Cabin in Colorado",
		City:          "Aspen",
		State:         "CO",
		ImageURL:      "https://picsum.photos/800/600?random=2",
		PricePerNight: 185.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.9, TotalReviews: 94},
	},
	{
		ID:            3,
		Title:         "Beachfront Condo in Miami",
		City:          "Miami Beach",
		State:         "FL",
		ImageURL:      "https://picsum.photos/800/600?random=3",
		PricePerNight: 275.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.6, TotalReviews: 202},
	},
	{
		ID:            4,
		Title:         "Stylish Apartment in New York",
		City:          "New York",
		State:         "NY",
		ImageURL:      "https://picsum.photos/800/600?random=4",
		PricePerNight: 320.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.8, TotalReviews: 330},
	},
	{
		ID:            5,
		Title:         "Desert Retreat in Arizona",
		City:          "Sedona",
		State:         "AZ",
		ImageURL:      "https://picsum.photos/800/600?random=5",
		PricePerNight: 160.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.5, TotalReviews: 71},
	},
	{
		ID:            6,
		Title:         "Lakehouse in Minnesota",
		City:          "Brainerd",
		State:         "MN",
		ImageURL:      "https://picsum.photos/800/600?random=6",
		PricePerNight: 190.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.9, TotalReviews: 58},
	},
	{
		ID:            7,
		Title:         "Mountain View Chalet",
		City:          "Jackson",
		State:         "WY",
		ImageURL:      "https://picsum.photos/800/600?random=7",
		PricePerNight: 240.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.7, TotalReviews: 115},
	},
	{
		ID:            8,
		Title:         "Tiny House in Portland",
		City:          "Portland",
		State:         "OR",
		ImageURL:      "https://picsum.photos/800/600?random=8",
		PricePerNight: 110.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.6, TotalReviews: 89},
	},
	{
		ID:            9,
		Title:         "Rustic Barn in Vermont",
		City:          "Stowe",
		State:         "VT",
		ImageURL:      "https://picsum.photos/800/600?random=9",
		PricePerNight: 135.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.8, TotalReviews: 76},
	},
	{
		ID:            10,
		Title:         "Luxury Villa in Malibu",
		City:          "Malibu",
		State:         "CA",
		ImageURL:      "https://picsum.photos/800/600?random=10",
		PricePerNight: 450.00,
		ReviewSummary: ReviewSummary{AverageRating: 5.0, TotalReviews: 51},
	},
}

var MockListingDetails = ListingDetails{
	ID:    1,
	Title: "Modern Loft in San Francisco",
	Location: Location{
		City:    "San Francisco",
		State:   "CA",
		ZipCode: "94103",
	},
	Pricing: Pricing{
		PricePerNight: 210,
	},
	Description: "Spacious loft with beautiful views...",
	Images: []string{
		"https://picsum.photos/800/600?random=1",
		"https://picsum.photos/800/600?random=2",
		"https://picsum.photos/800/600?random=3",
	},
	Amenities: []string{"WiFi", "Kitchen", "Washer", "Heating"},
	Host: Host{
		Name:      "Jane Doe",
		AvatarURL: "https://picsum.photos/800/600?random=4",
	},
	Review: ReviewSummary{
		AverageRating: 4.5,
		TotalReviews:  52,
	},
}

var MockListingReviews = map[int][]Review{
	1: {
		{
			Reviewer:  "Alice",
			Comment:   "Amazing stay!",
			Rating:    5,
			Date:      "2024-12-01",
			AvatarURL: "https://picsum.photos/seed/alice/64",
			TripType:  "Family",
			Location:  "Washington, SA",
		},
		{
			Reviewer:  "Bob",
			Comment:   "Nice place but a bit noisy.",
			Rating:    4,
			Date:      "2024-11-15",
			AvatarURL: "https://picsum.photos/seed/bob/64",
			TripType:  "Business",
			Location:  "Chicago, IL",
		},
		{
			Reviewer:  "Claire",
			Comment:   "Perfect for a weekend getaway.",
			Rating:    5,
			Date:      "2024-11-10",
			AvatarURL: "https://picsum.photos/seed/claire/64",
			TripType:  "Couple trip",
			Location:  "Denver, CO",
		},
		{
			Reviewer:  "Dan",
			Comment:   "Had everything we needed.",
			Rating:    5,
			Date:      "2024-10-20",
			AvatarURL: "https://picsum.photos/seed/dan/64",
			TripType:  "Solo trip",
			Location:  "Boston, MA",
		},
		{
			Reviewer:  "Eva",
			Comment:   "Great views and clean.",
			Rating:    4,
			Date:      "2024-10-05",
			AvatarURL: "https://picsum.photos/seed/eva/64",
			TripType:  "Group trip",
			Location:  "Portland, OR",
		},
		{
			Reviewer:  "Frank",
			Comment:   "Spacious and bright.",
			Rating:    5,
			Date:      "2024-09-28",
			AvatarURL: "https://picsum.photos/seed/frank/64",
			TripType:  "Family",
			Location:  "Atlanta, GA",
		},
	},
}
