package handlers

var MockListings = []Listing{
	{
		ID:            1,
		Title:         "Modern Loft in San Francisco",
		City:          "San Francisco",
		State:         "CA",
		ImageURL:      "https://picsum.photos/800/600?random=1",
		PricePerNight: 210.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.7, TotalReviews: 128},
	},
	{
		ID:            2,
		Title:         "Cozy Cabin in Colorado",
		City:          "Aspen",
		State:         "CO",
		ImageURL:      "https://picsum.photos/800/600?random=2",
		PricePerNight: 185.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.9, TotalReviews: 94},
	},
	{
		ID:            3,
		Title:         "Beachfront Condo in Miami",
		City:          "Miami Beach",
		State:         "FL",
		ImageURL:      "https://picsum.photos/800/600?random=3",
		PricePerNight: 275.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.6, TotalReviews: 202},
	},
	{
		ID:            4,
		Title:         "Stylish Apartment in New York",
		City:          "New York",
		State:         "NY",
		ImageURL:      "https://picsum.photos/800/600?random=4",
		PricePerNight: 320.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.8, TotalReviews: 330},
	},
	{
		ID:            5,
		Title:         "Desert Retreat in Arizona",
		City:          "Sedona",
		State:         "AZ",
		ImageURL:      "https://picsum.photos/800/600?random=5",
		PricePerNight: 160.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.5, TotalReviews: 71},
	},
	{
		ID:            6,
		Title:         "Lakehouse in Minnesota",
		City:          "Brainerd",
		State:         "MN",
		ImageURL:      "https://picsum.photos/800/600?random=6",
		PricePerNight: 190.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.9, TotalReviews: 58},
	},
	{
		ID:            7,
		Title:         "Mountain View Chalet",
		City:          "Jackson",
		State:         "WY",
		ImageURL:      "https://picsum.photos/800/600?random=7",
		PricePerNight: 240.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.7, TotalReviews: 115},
	},
	{
		ID:            8,
		Title:         "Tiny House in Portland",
		City:          "Portland",
		State:         "OR",
		ImageURL:      "https://picsum.photos/800/600?random=8",
		PricePerNight: 110.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.6, TotalReviews: 89},
	},
	{
		ID:            9,
		Title:         "Rustic Barn in Vermont",
		City:          "Stowe",
		State:         "VT",
		ImageURL:      "https://picsum.photos/800/600?random=9",
		PricePerNight: 135.00,
		ReviewSummary: ReviewSummary{AverageRating: 4.8, TotalReviews: 76},
	},
	{
		ID:            10,
		Title:         "Luxury Villa in Malibu",
		City:          "Malibu",
		State:         "CA",
		ImageURL:      "https://picsum.photos/800/600?random=10",
		PricePerNight: 450.00,
		ReviewSummary: ReviewSummary{AverageRating: 5.0, TotalReviews: 51},
	},
}

var MockListingDetails = ListingDetails{
	ID:    1,
	Title: "Modern Loft in San Francisco",
	Location: Location{
		City:    "San Francisco",
		State:   "CA",
		ZipCode: "94103",
	},
	Pricing: Pricing{
		PricePerNight: 210,
	},
	Description: "Spacious loft with beautiful views...",
	Images: []string{
		"https://picsum.photos/800/600?random=1",
		"https://picsum.photos/800/600?random=2",
		"https://picsum.photos/800/600?random=3",
	},
	Amenities: []string{"WiFi", "Kitchen", "Washer", "Heating"},
	Host: Host{
		Name:      "Jane Doe",
		AvatarURL: "https://picsum.photos/800/600?random=4",
	},
	Review: ReviewSummary{
		AverageRating: 4.5,
		TotalReviews:  52,
	},
}

var MockListingReviews = map[int][]Review{
	1: {
		{ReviewerID: "u1", Reviewer: "Alice", Comment: "Amazing stay!", Rating: 5, Date: "2024-12-01", AvatarURL: "https://picsum.photos/seed/alice/64", TripType: "Family", Location: "Washington, SA"},
		{ReviewerID: "u2", Reviewer: "Bob", Comment: "Nice place but a bit noisy.", Rating: 4, Date: "2024-11-15", AvatarURL: "https://picsum.photos/seed/bob/64", TripType: "Business", Location: "Chicago, IL"},
		{ReviewerID: "u3", Reviewer: "Claire", Comment: "Perfect for a weekend getaway.", Rating: 5, Date: "2024-11-10", AvatarURL: "https://picsum.photos/seed/claire/64", TripType: "Couple trip", Location: "Denver, CO"},
		{ReviewerID: "u4", Reviewer: "Dan", Comment: "Had everything we needed.", Rating: 5, Date: "2024-10-20", AvatarURL: "https://picsum.photos/seed/dan/64", TripType: "Solo trip", Location: "Boston, MA"},
		{ReviewerID: "u5", Reviewer: "Eva", Comment: "Great views and clean.", Rating: 4, Date: "2024-10-05", AvatarURL: "https://picsum.photos/seed/eva/64", TripType: "Group trip", Location: "Portland, OR"},
		{ReviewerID: "u6", Reviewer: "Frank", Comment: "Spacious and bright.", Rating: 5, Date: "2024-09-28", AvatarURL: "https://picsum.photos/seed/frank/64", TripType: "Family", Location: "Atlanta, GA"},
		{ReviewerID: "u7", Reviewer: "Grace", Comment: "Felt like home.", Rating: 5, Date: "2024-09-20", AvatarURL: "https://picsum.photos/seed/grace/64", TripType: "Solo trip", Location: "Austin, TX"},
		{ReviewerID: "u8", Reviewer: "Henry", Comment: "Too far from downtown.", Rating: 3, Date: "2024-09-14", AvatarURL: "https://picsum.photos/seed/henry/64", TripType: "Business", Location: "Phoenix, AZ"},
		{ReviewerID: "u9", Reviewer: "Ivy", Comment: "Very cozy and warm.", Rating: 5, Date: "2024-09-08", AvatarURL: "https://picsum.photos/seed/ivy/64", TripType: "Couple trip", Location: "Seattle, WA"},
		{ReviewerID: "u10", Reviewer: "Jack", Comment: "Could use better lighting.", Rating: 3, Date: "2024-08-29", AvatarURL: "https://picsum.photos/seed/jack/64", TripType: "Group trip", Location: "Nashville, TN"},
		{ReviewerID: "u11", Reviewer: "Kara", Comment: "Super clean and peaceful.", Rating: 5, Date: "2024-08-21", AvatarURL: "https://picsum.photos/seed/kara/64", TripType: "Family", Location: "San Diego, CA"},
		{ReviewerID: "u12", Reviewer: "Leo", Comment: "Friendly host, great location.", Rating: 4, Date: "2024-08-12", AvatarURL: "https://picsum.photos/seed/leo/64", TripType: "Business", Location: "Las Vegas, NV"},
		{ReviewerID: "u13", Reviewer: "Maya", Comment: "Small but cute.", Rating: 4, Date: "2024-08-01", AvatarURL: "https://picsum.photos/seed/maya/64", TripType: "Couple trip", Location: "Miami, FL"},
		{ReviewerID: "u14", Reviewer: "Noah", Comment: "Love the balcony view!", Rating: 5, Date: "2024-07-27", AvatarURL: "https://picsum.photos/seed/noah/64", TripType: "Solo trip", Location: "Salt Lake City, UT"},
		{ReviewerID: "u15", Reviewer: "Olivia", Comment: "Walkable to everything!", Rating: 5, Date: "2024-07-15", AvatarURL: "https://picsum.photos/seed/olivia/64", TripType: "Family", Location: "Philadelphia, PA"},
		{ReviewerID: "u16", Reviewer: "Paul", Comment: "Bit outdated but okay.", Rating: 3, Date: "2024-07-04", AvatarURL: "https://picsum.photos/seed/paul/64", TripType: "Group trip", Location: "Cleveland, OH"},
		{ReviewerID: "u17", Reviewer: "Quinn", Comment: "Super fast Wi-Fi!", Rating: 5, Date: "2024-06-26", AvatarURL: "https://picsum.photos/seed/quinn/64", TripType: "Business", Location: "Orlando, FL"},
		{ReviewerID: "u18", Reviewer: "Rachel", Comment: "Modern and stylish decor.", Rating: 5, Date: "2024-06-14", AvatarURL: "https://picsum.photos/seed/rachel/64", TripType: "Couple trip", Location: "Minneapolis, MN"},
		{ReviewerID: "u19", Reviewer: "Sam", Comment: "The AC was too loud.", Rating: 3, Date: "2024-06-02", AvatarURL: "https://picsum.photos/seed/sam/64", TripType: "Solo trip", Location: "Sacramento, CA"},
		{ReviewerID: "u20", Reviewer: "Tina", Comment: "Pet friendly, loved it!", Rating: 5, Date: "2024-05-28", AvatarURL: "https://picsum.photos/seed/tina/64", TripType: "Family", Location: "Charlotte, NC"},

		{ReviewerID: "u21", Reviewer: "Uma", Comment: "Clean and convenient.", Rating: 4, Date: "2024-05-20", AvatarURL: "https://picsum.photos/seed/uma/64", TripType: "Business", Location: "Cincinnati, OH"},
		{ReviewerID: "u22", Reviewer: "Victor", Comment: "Funky design!", Rating: 4, Date: "2024-05-11", AvatarURL: "https://picsum.photos/seed/victor/64", TripType: "Couple trip", Location: "New Orleans, LA"},
		{ReviewerID: "u23", Reviewer: "Wendy", Comment: "Basic but worked for us.", Rating: 3, Date: "2024-05-01", AvatarURL: "https://picsum.photos/seed/wendy/64", TripType: "Solo trip", Location: "Detroit, MI"},
		{ReviewerID: "u24", Reviewer: "Xavier", Comment: "Would stay again!", Rating: 5, Date: "2024-04-21", AvatarURL: "https://picsum.photos/seed/xavier/64", TripType: "Family", Location: "Houston, TX"},
		{ReviewerID: "u25", Reviewer: "Yara", Comment: "Too small for our group.", Rating: 2, Date: "2024-04-10", AvatarURL: "https://picsum.photos/seed/yara/64", TripType: "Group trip", Location: "Baltimore, MD"},
		{ReviewerID: "u26", Reviewer: "Zack", Comment: "Fantastic location!", Rating: 5, Date: "2024-03-30", AvatarURL: "https://picsum.photos/seed/zack/64", TripType: "Business", Location: "St. Louis, MO"},
		{ReviewerID: "u27", Reviewer: "Amy", Comment: "Lots of natural light.", Rating: 4, Date: "2024-03-18", AvatarURL: "https://picsum.photos/seed/amy/64", TripType: "Couple trip", Location: "Raleigh, NC"},
		{ReviewerID: "u28", Reviewer: "Ben", Comment: "Quiet neighborhood.", Rating: 5, Date: "2024-03-05", AvatarURL: "https://picsum.photos/seed/ben/64", TripType: "Solo trip", Location: "Tucson, AZ"},
		{ReviewerID: "u29", Reviewer: "Cindy", Comment: "Nice for short stay.", Rating: 4, Date: "2024-02-23", AvatarURL: "https://picsum.photos/seed/cindy/64", TripType: "Group trip", Location: "Indianapolis, IN"},
		{ReviewerID: "u30", Reviewer: "Derek", Comment: "Great for remote work.", Rating: 5, Date: "2024-02-12", AvatarURL: "https://picsum.photos/seed/derek/64", TripType: "Business", Location: "Columbus, OH"},
		{ReviewerID: "u31", Reviewer: "Ella", Comment: "Very disappointing experience.", Rating: 1, Date: "2024-02-01", AvatarURL: "https://picsum.photos/seed/ella/64", TripType: "Solo trip", Location: "Memphis, TN"},
		{ReviewerID: "u32", Reviewer: "Felix", Comment: "Friendly host but noisy neighbors.", Rating: 2, Date: "2024-01-25", AvatarURL: "https://picsum.photos/seed/felix/64", TripType: "Business", Location: "Milwaukee, WI"},
		{ReviewerID: "u33", Reviewer: "Gina", Comment: "Lovely garden area.", Rating: 4, Date: "2024-01-15", AvatarURL: "https://picsum.photos/seed/gina/64", TripType: "Family", Location: "Louisville, KY"},
		{ReviewerID: "u34", Reviewer: "Harry", Comment: "Close to all attractions.", Rating: 5, Date: "2024-01-05", AvatarURL: "https://picsum.photos/seed/harry/64", TripType: "Couple trip", Location: "Virginia Beach, VA"},
		{ReviewerID: "u35", Reviewer: "Isla", Comment: "Could be cleaner.", Rating: 3, Date: "2023-12-28", AvatarURL: "https://picsum.photos/seed/isla/64", TripType: "Group trip", Location: "Albuquerque, NM"},
		{ReviewerID: "u36", Reviewer: "Jake", Comment: "Nice kitchen setup.", Rating: 4, Date: "2023-12-19", AvatarURL: "https://picsum.photos/seed/jake/64", TripType: "Business", Location: "Fresno, CA"},
		{ReviewerID: "u37", Reviewer: "Kylie", Comment: "Beds were not comfortable.", Rating: 2, Date: "2023-12-10", AvatarURL: "https://picsum.photos/seed/kylie/64", TripType: "Family", Location: "Sacramento, CA"},
		{ReviewerID: "u38", Reviewer: "Liam", Comment: "Great value for money.", Rating: 5, Date: "2023-11-29", AvatarURL: "https://picsum.photos/seed/liam/64", TripType: "Solo trip", Location: "Kansas City, MO"},
		{ReviewerID: "u39", Reviewer: "Mona", Comment: "Friendly neighborhood.", Rating: 4, Date: "2023-11-20", AvatarURL: "https://picsum.photos/seed/mona/64", TripType: "Couple trip", Location: "Mesa, AZ"},
		{ReviewerID: "u40", Reviewer: "Nate", Comment: "Parking was difficult.", Rating: 3, Date: "2023-11-10", AvatarURL: "https://picsum.photos/seed/nate/64", TripType: "Business", Location: "Atlanta, GA"},
		{ReviewerID: "u41", Reviewer: "Olga", Comment: "Loved the fireplace!", Rating: 5, Date: "2023-11-02", AvatarURL: "https://picsum.photos/seed/olga/64", TripType: "Family", Location: "Omaha, NE"},
		{ReviewerID: "u42", Reviewer: "Pete", Comment: "Was not as described.", Rating: 2, Date: "2023-10-24", AvatarURL: "https://picsum.photos/seed/pete/64", TripType: "Group trip", Location: "Reno, NV"},
		{ReviewerID: "u43", Reviewer: "Quincy", Comment: "Excellent communication.", Rating: 5, Date: "2023-10-15", AvatarURL: "https://picsum.photos/seed/quincy/64", TripType: "Solo trip", Location: "Birmingham, AL"},
		{ReviewerID: "u44", Reviewer: "Rose", Comment: "Great for families.", Rating: 4, Date: "2023-10-06", AvatarURL: "https://picsum.photos/seed/rose/64", TripType: "Family", Location: "Tampa, FL"},
		{ReviewerID: "u45", Reviewer: "Steve", Comment: "No hot water.", Rating: 1, Date: "2023-09-28", AvatarURL: "https://picsum.photos/seed/steve/64", TripType: "Business", Location: "Wichita, KS"},
		{ReviewerID: "u46", Reviewer: "Tara", Comment: "Convenient and cozy.", Rating: 5, Date: "2023-09-18", AvatarURL: "https://picsum.photos/seed/tara/64", TripType: "Couple trip", Location: "Aurora, CO"},
		{ReviewerID: "u47", Reviewer: "Uri", Comment: "Very modern design.", Rating: 4, Date: "2023-09-08", AvatarURL: "https://picsum.photos/seed/uri/64", TripType: "Solo trip", Location: "Anaheim, CA"},
		{ReviewerID: "u48", Reviewer: "Vera", Comment: "Noisy at night.", Rating: 2, Date: "2023-08-30", AvatarURL: "https://picsum.photos/seed/vera/64", TripType: "Group trip", Location: "Santa Ana, CA"},
		{ReviewerID: "u49", Reviewer: "Will", Comment: "Easy check-in process.", Rating: 5, Date: "2023-08-20", AvatarURL: "https://picsum.photos/seed/will/64", TripType: "Business", Location: "Corpus Christi, TX"},
		{ReviewerID: "u50", Reviewer: "Xena", Comment: "Could improve Wi-Fi.", Rating: 3, Date: "2023-08-10", AvatarURL: "https://picsum.photos/seed/xena/64", TripType: "Family", Location: "Lexington, KY"},
		{ReviewerID: "u51", Reviewer: "Yosef", Comment: "Amazing hospitality!", Rating: 5, Date: "2023-07-31", AvatarURL: "https://picsum.photos/seed/yosef/64", TripType: "Couple trip", Location: "Henderson, NV"},
		{ReviewerID: "u52", Reviewer: "Zoe", Comment: "Clean, comfortable, recommended.", Rating: 5, Date: "2023-07-22", AvatarURL: "https://picsum.photos/seed/zoe/64", TripType: "Solo trip", Location: "Stockton, CA"},
	},
}
